apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: bar
    count: 2

configMapGenerator:
- name: env-bar
  envs:
  - env
  behavior: merge

