apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: foo
    count: 2

configMapGenerator:
- name: env-foo
  envs:
  - env
  behavior: merge

