apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: foo
        image: registry.k8s.io/ubuntu-slim:0.1
        stdin: true
        tty: true
        envFrom:
        - configMapRef:
            name: env-foo
        command: ["/bin/sh"]
        args:
          - "-c"
          - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"
#        resources:
#          requests:
#            memory: 64Mi
#            cpu: 250m
#          limits:
#            memory: 64Mi
#            cpu: 250m

