apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app: foo
  distributed: required

resources:
  - deployment.yaml

configMapGenerator:
- name: env-foo
  envs:
  - env

